### PR TITLE
duration constraint enabled and tests

### PR DESCRIPTION
**Pull request by chkwon**
As discussed, I enabled the duration constraint macro and used CMT6 and CMT7 to test duration constrained instances. I also used a random instance to test in `test.c`.

### CODE REVIEW

**Comment by vidalt** [comment]
Hello @chkwon, thanks again for the great contribution, and my apologies for the delay. The pull request looks great, I will integrate it right now. In the future, I noticed that sometimes our conventions regarding the display of solution values are not consistent:

image

Usually, we compute solution values (and check constraints) with full precision when distances are not rounded. Only when displaying the final solution values, it is common in papers to report two significant digits. Perhaps we could make sure that a similar convention is satisfied through the code, as well as in the tests scripts. This could help avoid possible issues when validating the results, e.g., 909.675 possibly not recognized as 909.68 in asserts, etc...

**Comment by chkwon** [comment]
Thanks. As you said, 909.675 seems like the value with full precision. But as a solver/library, I think it should return the value with full precision, not a rounded value. It must be the user's responsibility to round appropriately. 

But I share your concern about testing. As you see below, I used 909.675 as a benchmark value. 
https://github.com/vidalt/HGS-CVRP/blob/2dcd92763e0075e88027197be3d8c51cbd94d778/CMakeLists.txt#L45-L49

**Comment by vidalt** [comment]
Sounds good, I agree that the solver should return full precision results.
What is the accuracy/tolerance of the value check in the test?

**Comment by chkwon** [comment]
In the test, I used whatever the value was written in the output `.sol` file.  Currently, in both displaying the cost on screen and writing it on a file, it uses `<<` operator to the stream. It has the precision of 6 (all significant digits). As a result for CMT7 it is `909.675`.

https://github.com/vidalt/HGS-CVRP/blob/ed0f3507bc9fa303a84d5d10997ec677eca65a6e/Program/Individual.cpp#L68

https://github.com/vidalt/HGS-CVRP/blob/ed0f3507bc9fa303a84d5d10997ec677eca65a6e/Program/Individual.cpp#L81

The actual value of `myCostSol.penalizedCost` is `909.675053`.

**Pull request merged**
