### PR TITLE
creating AlgorithmParameters

### PR DESCRIPTION
**Pull request by chkwon**
- To create an instance of `Params`, now we need to create and pass `AlgorithmParameters`
- All default parameter values are stored in one place in the code: `AlgorithmParameters.cpp`

I didn't include `increasePenalty`, `decreasePenalty`, and `repairProb`, due to potential behavior changes.  In the current code:
https://github.com/vidalt/HGS-CVRP/blob/6c1f09b6c28a7070a5cc0c9faed4bfecde52fce8/Program/Genetic.cpp#L14
`std::rand()%2==0` is used to represent 0.5. If I change to a more general expression for `repairProb`, for example:
`std::rand() / RAND_MAX <= 0.5` I am afraid that it could change the code behavior.

So, at least for now, only the major algorithm parameters that you suggested are included.

### CODE REVIEW

**Comment by vidalt** [comment]
I noticed a tiny bug in the display of parameter values here:
https://github.com/vidalt/HGS-CVRP/runs/5656526215?check_suite_focus=true#step:4:31

**Comment by vidalt** [comment]
While checking, I also noted something weird [here](https://github.com/chkwon/HGS-CVRP/blob/1acdcd535f75b2a09e9ec5e7b2f265faebea9719/Program/Params.cpp#L37)
- The custNum variable would take 0 for the first customer, which is not the convention in the algorithm (depot is 0, followed by customers 1...n).  It seems actually that this variable is now deprecated, and could be removed entirely.
- Additionally it is possible to add a simple security check (exception) [here](https://github.com/chkwon/HGS-CVRP/blob/1acdcd535f75b2a09e9ec5e7b2f265faebea9719/Program/CVRPLIB.cpp#L43) where we compare custNum (read from the file) to i+1 and raise an exception if this does not match.

**Comment by vidalt** [comment]
All the other changes look great

**Comment by chkwon** [comment]
`custNum` is removed. When it reads from .vrp files, `custNum` variable was just a dummy variable that reads the node number in the .vrp file. I changed it to `node_number` and added explanation not to be confused in the future.

**Comment by vidalt** [comment]
Thanks a lot! I will now merge the pull request.

**Pull request merged**
